import { SCOPE } from '../../constants';

export const FETCH_STREETNAME_REQUEST = `${SCOPE}/LocationPage/FETCH_STREETNAME_REQUEST`;
export const FETCH_STREETNAME_SUCCESS = `${SCOPE}/LocationPage/FETCH_STREETNAME_SUCCESS`;
export const FETCH_STREETNAME_FAILURE = `${SCOPE}/LocationPage/FETCH_STREETNAME_FAILURE`;

export const FETCH_BAG_REQUEST = `${SCOPE}/LocationPage/FETCH_BAG_REQUEST`;
export const FETCH_BAG_SUCCESS = `${SCOPE}/LocationPage/FETCH_BAG_SUCCESS`;
export const FETCH_BAG_NO_RESULTS = `${SCOPE}/LocationPage/FETCH_BAG_NO_RESULTS`;
export const FETCH_BAG_FAILURE = `${SCOPE}/LocationPage/FETCH_BAG_FAILURE`;

export const FETCH_MONUMENT_REQUEST = `${SCOPE}/LocationPage/FETCH_MONUMENT_REQUEST`;
export const FETCH_MONUMENT_SUCCESS = `${SCOPE}/LocationPage/FETCH_MONUMENT_SUCCESS`;
export const FETCH_MONUMENT_FAILURE = `${SCOPE}/LocationPage/FETCH_MONUMENT_FAILURE`;

export const FETCH_STADSGEZICHT_REQUEST = `${SCOPE}/LocationPage/FETCH_STADSGEZICHT_REQUEST`;
export const FETCH_STADSGEZICHT_SUCCESS = `${SCOPE}/LocationPage/FETCH_STADSGEZICHT_SUCCESS`;
export const FETCH_STADSGEZICHT_FAILURE = `${SCOPE}/LocationPage/FETCH_STADSGEZICHT_FAILURE`;

export const FETCH_BEPERKING_REQUEST = `${SCOPE}/LocationPage/FETCH_BEPERKING_REQUEST`;
export const FETCH_BEPERKING_SUCCESS = `${SCOPE}/LocationPage/FETCH_BEPERKING_SUCCESS`;
export const FETCH_BEPERKING_FAILURE = `${SCOPE}/LocationPage/FETCH_BEPERKING_FAILURE`;

export const FETCH_BESTEMMINGSPLAN_REQUEST = `${SCOPE}/LocationPage/FETCH_BESTEMMINGSPLAN_REQUEST`;
export const FETCH_BESTEMMINGSPLAN_SUCCESS = `${SCOPE}/LocationPage/FETCH_BESTEMMINGSPLAN_SUCCESS`;
export const FETCH_BESTEMMINGSPLAN_FAILURE = `${SCOPE}/LocationPage/FETCH_BESTEMMINGSPLAN_FAILURE`;
