---
- name: deploy vergunningschecker
  hosts: dockers # see inventory.ini
  tags: docker
  any_errors_fatal: True

  serial: # deploy 1 host at a time
    - 1
    - "100%"

  vars:
    app_name: vergunningschecker
    app_port: "{{ app_list['vergunningschecker']['port'] }}"
    haproxy_cluster: cluster_vergunningschecker
    health_page: http://localhost:{{ app_port }}/

  # disable services
  pre_tasks:
    - include_tasks: tasks/consul.yml
      vars:
        action: disable
    - include_tasks: tasks/haproxy.yml
      vars:
        action: disable

  # do actual deploy
  tasks:
    - name: Deploy vergunningschecker frontend
      docker_container:
        name: "{{ app_name }}-client"
        image: "{{ global_registry }}/ois/{{ app_name }}-client:{{ global_environment }}"
        state: started
        pull: yes
        restart_policy: always
        log_driver: json-file # ??????????????? elastic
        published_ports:
          - "{{ app_port }}:80"
        dns_servers: "{{ ansible_docker0.ipv4.address }}"
      become: yes

    - name: Redis
      docker_container:
        image: redis

    - name: Deploy vergunningschecker backend
      docker_container:
        name: "{{ app_name }}-graphql"
        image: "{{ global_registry }}/ois/{{ app_name }}-graphql:{{ global_environment }}"
        state: started
        pull: yes
        restart_policy: always
        log_driver: json-file # ??????????????? elastic
        published_ports:
          - "{{ app_port }}:80"
        dns_servers: "{{ ansible_docker0.ipv4.address }}"
      become: yes
      links:
        - redis

  post_tasks:
    - include_tasks: tasks/wait_check.yml
    - include_tasks: tasks/consul.yml
      vars:
        action: enable
    - include_tasks: tasks/haproxy.yml
      vars:
        action: enable
