---
- name: Wait for the service to come up
  wait_for:
    host: "localhost"
    state: started
    port: "{{ app_port }}"
    delay: "{{ wait_time | default(20) }}"
    timeout: "{{ timeout | default(60) }}"
    connect_timeout: 5
- name: Health check
  uri:
    url: "{{ health_page }}"
    timeout: "{{ timeout_health | default(30) }}"
    status_code: "{{ status_code | default([200]) }}"
  retries: 5
  when: healthcheck is not defined
