FROM node:alpine AS base
LABEL maintainer="datapunt@amsterdam.nl"

# It would be more secure to run under user 'node'
# USER node

WORKDIR /app/
COPY apps/graphql/package*.json ./

# Test
# FROM base AS builder
# RUN npm ci
# COPY apps/graphql/ .
# RUN npm run test

# Release
FROM base
ARG NODE_ENV
RUN npm ci
COPY apps/graphql/ .
ENV PORT=80
CMD node .