FROM node:alpine AS base
LABEL maintainer="datapunt@amsterdam.nl"

WORKDIR /app/
COPY apps/graphql/package*.json ./

# Test
# FROM base AS builder
# RUN npm ci
# COPY apps/graphql/ .
# RUN npm run test

# Release
FROM base
ARG NODE_ENV
RUN npm ci --no-color -q
COPY apps/graphql/ .
USER node
ENV PORT=8080
CMD node .
