version: "3.7"

services:
  proxy:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx-proxy.default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend-network
      - frontend-network

  client:
    build:
      context: ..
      dockerfile: ci/Dockerfile.client
    restart: unless-stopped
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - frontend-network

  graphql:
    build:
      context: ..
      dockerfile: ci/Dockerfile.graphql
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
    restart: unless-stopped
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 1s
    networks:
      - backend-network
      - redis-network

  redis:
    restart: unless-stopped
    image: redis
    networks:
      - redis-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
  redis-network:
    driver: bridge
