version: "3.7"

services:
  client:
    build:
      context: ..
      dockerfile: ci/Dockerfile.client
    ports:
      - "${PORT}:80"
    restart: unless-stopped
    environment:
      NAMESERVER: 127.0.0.11
      BACKEND_URI: http://graphql:8080/graphql
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend-network
      - frontend-network

  graphql:
    build:
      context: ..
      dockerfile: ci/Dockerfile.graphql
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
    restart: unless-stopped
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 1s
    networks:
      - backend-network
      - redis-network

  redis:
    restart: unless-stopped
    image: redis
    networks:
      - redis-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
  redis-network:
    driver: bridge
