// def tryStep(String message, Closure block) {
//   try {
//     block()
//   } catch (Throwable t) {
//     slackSend message: "${env.JOB_NAME}: ${message} failure ${env.BUILD_URL}", channel: '#ci-channel', color: 'danger'
//     // slackSend message: "${env.JOB_NAME}: ${message} failure ${env.BUILD_URL}", channel: '#ci-chappie', color: 'danger'
//     throw t
//   }
// }

// node {
//   stage("Checkout") {
//     checkout scm
//   }
// }

// if (env.BRANCH_NAME == "chappie1.0") {
//   // not tested, pseudo code!

//   node {
//     def imageUrl = "build.app.amsterdam.nl:5000/ois/vergunningschecker:${env.BUILD_NUMBER}";
//     // stage("Checkout") {
//     //   checkout scm
//     // }
//     stage("Build") {
//       tryStep "build", {
//         docker.build("${imageUrl} --build-arg NODE_ENV=production -f ci/Dockerfile .").push("chappie1.0")
//       }
//     }
//     stage("Deploy") {
//       tryStep "deploy", {
//         build job: 'Subtask_Openstack_Playbook',
//         parameters: [
//           [$class: 'StringParameterValue', name: 'INVENTORY', value: 'acceptance'],
//           [$class: 'StringParameterValue', name: 'PLAYBOOK', value: 'deploy-vergunningschecker.yml'],
//         ]
//       }
//     }
//   }
// } else {
//   node {
//     stage("Build image") {
//       timeout(10) {
//         tryStep "build", {
//           def image = docker.build("build.app.amsterdam.nl:5000/ois/vergunningschecker:${env.BUILD_NUMBER} .")
//           image.push()
//         }
//       }
//     }
//   }


//   if (env.BRANCH_NAME == "master") {
//     node {
//       stage('Push acceptance image') {
//         tryStep "image tagging", {
//           def image = docker.image("build.app.amsterdam.nl:5000/ois/vergunningschecker:${env.BUILD_NUMBER}")
//           image.pull()
//           image.push("acceptance")
//         }
//       }
//     }

//     node {
//       stage("Deploy to ACC") {
//         tryStep "deployment", {
//           build job: 'Subtask_Openstack_Playbook',
//           parameters: [
//             [$class: 'StringParameterValue', name: 'INVENTORY', value: 'acceptance'],
//             [$class: 'StringParameterValue', name: 'PLAYBOOK', value: 'deploy-vergunningschecker.yml'],
//           ]
//         }
//       }
//     }

//     stage('Waiting for approval') {
//       slackSend channel: '#ci-channel', color: 'warning', message: 'vergunningschecker is waiting for Production Release - please confirm'
//       timeout(10) {
//         input "Deploy to Production?"
//       }
//     }

//     node {
//       stage("Build and Push Production image") {
//         tryStep "build", {
//           def image = docker.build("build.app.amsterdam.nl:5000/ois/vergunningschecker:${env.BUILD_NUMBER}",
//             "--shm-size 1G " +
//             "--build-arg BUILD_NUMBER=${env.BUILD_NUMBER} " +
//             ".")
//           image.push("production")
//           image.push("latest")
//         }
//       }
//     }

//     node {
//       stage("Deploy") {
//         tryStep "deployment", {
//           build job: 'Subtask_Openstack_Playbook',
//           parameters: [
//             [$class: 'StringParameterValue', name: 'INVENTORY', value: 'production'],
//             [$class: 'StringParameterValue', name: 'PLAYBOOK', value: 'deploy-vergunningschecker.yml'],
//           ]
//         }
//       }
//     }
//   }

//   if (env.BRANCH_NAME == "develop") {
//     node {
//       stage('Push acceptance image') {
//         tryStep "image tagging", {
//           def image = docker.image("build.app.amsterdam.nl:5000/ois/vergunningschecker:${env.BUILD_NUMBER}")
//           image.pull()
//           image.push("acceptance")
//         }
//       }
//     }

//     node {
//       stage("Deploy to ACC") {
//         tryStep "deployment", {
//           build job: 'Subtask_Openstack_Playbook',
//           parameters: [
//             [$class: 'StringParameterValue', name: 'INVENTORY', value: 'acceptance'],
//             [$class: 'StringParameterValue', name: 'PLAYBOOK', value: 'deploy-vergunningschecker.yml'],
//           ]
//         }
//       }
//   }
// }
